/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as linearSol from "./Linear.sol";
export type { linearSol };
import type * as polynomialSol from "./Polynomial.sol";
export type { polynomialSol };
